global:
  imagePullPolicy: IfNotPresent

app:
  gateway:
    enabled: true
    image: { repository: gateway-bff, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      ACCOUNT_BASE_URL: http://account:80
      OIDC_AUTHORIZATION_URI: http://keycloak:8080/realms/miniserversystem/protocol/openid-connect/auth
      OIDC_TOKEN_URI: http://keycloak:8080/realms/miniserversystem/protocol/openid-connect/token
      OIDC_USER_INFO_URI: http://keycloak:8080/realms/miniserversystem/protocol/openid-connect/userinfo
      OIDC_JWK_SET_URI: http://keycloak:8080/realms/miniserversystem/protocol/openid-connect/certs
      OIDC_CLIENT_ID: gateway-bff
      OIDC_CLIENT_SECRET: changeit
      ACCOUNT_INTERNAL_API_TOKEN: changeit-internal

  account:
    enabled: true
    image: { repository: account, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem
      ACCOUNT_INTERNAL_API_TOKEN: changeit-internal

  entitlement:
    enabled: true
    image: { repository: entitlement, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem
      NATS_URL: nats://nats:4222

  matchmaking:
    enabled: true
    image: { repository: matchmaking, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      NATS_URL: nats://nats:4222

  notification:
    enabled: true
    strategy: Recreate
    image: { repository: notification, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem
      NATS_URL: nats://nats:4222

ingress:
  enabled: false
