global:
  imagePullPolicy: IfNotPresent

app:
  gateway:
    enabled: true
    image: { repository: gateway-bff, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      ACCOUNT_BASE_URL: http://account:80
      OIDC_ISSUER: http://keycloak:8080/realms/miniserversystem
      OIDC_CLIENT_ID: gateway-bff
      OIDC_CLIENT_SECRET: changeit

  account:
    enabled: true
    image: { repository: account, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem

  entitlement:
    enabled: true
    image: { repository: entitlement, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem
      NATS_URL: nats://nats:4222

  matchmaking:
    enabled: true
    image: { repository: matchmaking, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      NATS_URL: nats://nats:4222

  notification:
    enabled: true
    image: { repository: notification, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem
      NATS_URL: nats://nats:4222

ingress:
  enabled: false
