global:
  imagePullPolicy: IfNotPresent

app:
  gateway:
    enabled: true
    image: { repository: gateway-bff, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      ACCOUNT_BASE_URL: http://account:80
      OIDC_ISSUER: https://accounts.google.com
      OIDC_AUTHORIZATION_ENDPOINT: https://accounts.google.com/o/oauth2/v2/auth
      OIDC_TOKEN_ENDPOINT: https://oauth2.googleapis.com/token
      OIDC_JWKS_URI: https://www.googleapis.com/oauth2/v3/certs
      OIDC_CLIENT_ID: ""
      OIDC_CLIENT_SECRET: ""
      OIDC_REDIRECT_URI: http://localhost:18080/callback

  account:
    enabled: true
    image: { repository: account, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem

  entitlement:
    enabled: true
    image: { repository: entitlement, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem
      NATS_URL: nats://nats:4222

  matchmaking:
    enabled: true
    image: { repository: matchmaking, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      NATS_URL: nats://nats:4222

  notification:
    enabled: true
    image: { repository: notification, tag: ci }
    port: 8080
    servicePort: 80
    env:
      SPRING_PROFILES_ACTIVE: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: miniserversystem
      POSTGRES_USER: miniserversystem
      POSTGRES_PASSWORD: miniserversystem
      NATS_URL: nats://nats:4222

ingress:
  enabled: false
