spring:
  config:
      activate:
        on-profile: local

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:miniserversystem}
    username: ${POSTGRES_USER:miniserversystem}
    password: ${POSTGRES_PASSWORD:miniserversystem}
    hikari:
      schema: entitlement

  flyway:
    enabled: true

nats:
  enabled: true
  url: ${NATS_URL:nats://localhost:4222}
