spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB:miniserversystem}
    username: ${POSTGRES_USER:miniserversystem}
    password: ${POSTGRES_PASSWORD:miniserversystem}

  flyway:
    enabled: true
    locations: classpath:db/migration

    create-schemas: true
    default-schema: entitlement
    schemas: entitlement
    table: flyway_schema_history_entitlement

    connect-retries: 30
    connect-retries-interval: 2s
