spring:
  config.activate.on-profile: test
  flyway:
    enabled: false

nats:
  enabled: false

notification:
  retention:
    enabled: false
  delivery:
    enabled: false
    failure-injection:
      enabled: false
      user-id-prefix: ""
