{{- range $name, $svc := .Values.app }}
{{- if $svc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
spec:
  {{- if $svc.strategy }}
  strategy:
    type: {{ $svc.strategy }}
  {{- end }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
      {{- if $.Values.istio.enabled }}
      annotations:
        sidecar.istio.io/inject: "true"
      {{- end }}
    spec:
      serviceAccountName: {{ default $name $svc.serviceAccountName }}
      containers:
        - name: {{ $name }}
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ $svc.port }}
          env:
            {{- range $k, $v := $svc.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ $svc.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ $svc.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
---
{{- end }}
{{- end }}
