resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - otel-collector.yaml
  - prometheus.yaml
  - grafana.yaml
  - keycloak.yaml
  - keycloak-ingress.yaml
  - network-policies.yaml
