resources:
  - ../../base
  - keycloak-realm-configmap.yaml
patches:
  - path: postgres-ephemeral.yaml
  - path: nats-ephemeral.yaml
  - path: keycloak-bootstrap-patch.yaml
  - path: nats-networkpolicy-e2e-patch.yaml
    target:
      kind: NetworkPolicy
      name: nats-allow-apps-only
