apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: miniserversystem
spec:
  template:
    spec:
      volumes:
        - name: nats-data
          emptyDir: null
          persistentVolumeClaim:
            claimName: nats-data
